version: "3.8"

services:
  db:
    image: postgis/postgis:13-3.1
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/postgresql/data
  graphql-engine:
    image: hasura/graphql-engine:v2.0.9.cli-migrations-v3
    ports:
      - "8080:8080"
    depends_on:
      - "db"
    restart: always
    env_file: .env

volumes:
  db_data: